2410-Capstone/DiscogMVP

- .env
- node_modules/.package-lock.json
- package-lock.json
- package.json
- server/db.js
This is what I have currently can database
> Db file branch

- server/db.js
Completed the create tables function. Let me know if anyone has any comments or anything that needs to be changed.
> Db file branch2

- server/db/carts.js
- server/db/client.js
- server/db/db.js
- server/db/orders.js
- server/db/products.js
- server/db/users.js
In regards to updateProduct, I am researching how to update multiple fields in one go, not just *every* field. But I can stick to updating specific/every field like previous workshops if you all think that's easier? Let me know.
> CRUD operations in products.js

- server/db/admin.js
- server/db/carts.js
- server/db/orders.js
- server/db/payments.js
> Forgot to commit changes?

- client/src/App.jsx
--- 
> Accidentally wrapped routes in another router when `main.jsx` had that covered.
> Router fix

- .env.example
- node_modules/.package-lock.json
- package-lock.json
- package.json
npm i helmet express-rate-limit express-validator
> Created .env.example to copy to .env when deleted

- .env.backup
- .gitignore
- server/db/admin.js
- server/db/carts.js
- server/db/db.js
- server/db/orders.js
- server/db/payments.js
- server/db/pool.js
- server/db/products.js
- server/db/seed.js
- server/db/users.js
Added return users;
return products;
something with my dotenv was weird. again. hopefully doesnt affect anything.
> Changed client.connect to pool.connect in helper functions

- server/db/db.js
- server/db/seed.js
- tests/orders.test.js
- tests/products.test.js
- tests/users.test.js
This fix was completely unintentional:
THE ONE TEST I HAVE WRITTEN IS STILL FAILING so please ignore that.
But in order to get my tests to pass, I had to rework some of `seed.js.`
Good news though, we're seeing `cartProductSample` and `orderProductSample` objects in the terminal when running `node seed.js`
ChatGPT helped me there
> Fix seed script to prevent undefined product IDs in cart/order items

- server/API.js
- server/db/db.js
- server/db/seed.js
- server/middleware/isAdminMiddleware.js
- server/middleware/productRoutes.js
- server/middleware/userRoutes.js
- tests/products.test.js
Fixed image to image_url in productRoutes
Added an admin user index 0 in createUser functions in seed.js
> Working on products unit tests

- client/src/App.jsx
- client/src/main.jsx
- client/src/pages/LogRegAuth/Login.jsx
- client/src/pages/LogRegAuth/OAuthLogin.jsx
- client/src/styles/scss/components/_reg_log.scss
- node_modules/.package-lock.json
- package-lock.json
- package.json
- server/middleware/authRoutes.js
>  Google client ID created and integrated into project. Next step is configuring creation of user profile based on Google account information.
> Google Login

- server/db/carts.js
- server/db/functionExports.js
- server/middleware/authMiddleware.js
- server/middleware/authRoutes.js
- server/middleware/cartRoutes.js
Sorry this commit is a mess. Long afternoon of debugging. Did not want to push anything that was not functioning. The cartRoutes have been tested in postman and are working. Need to write unit tests.
> Created cartRoutes.js for RESTful API routes and unit tests

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/main.jsx
- client/src/pages/LogRegAuth/OAuthLogin.jsx
- server/API.js
- server/middleware/authRoutes.js
- server/startServer.js
- server/utils/googleAuthController.js
> Pushing to add current GoogleAuth progress for functional preview
> Pushing to add current GoogleAuth progress for functional preview

- node_modules/.package-lock.json
- package-lock.json
- package.json
- server/API.js
- server/middleware/authRoutes.js
- server/middleware/isAdminMiddleware.js
- server/middleware/orderRoutes.js
- server/middleware/paymentRoutes.js
- server/middleware/productRoutes.js
- server/middleware/userRoutes.js
- tests/carts.test.js
- tests/payments.test.js
- tests/users.test.js
fixed import path for googleOAuth so terminal would stop screaming
> carts.test.js unit tests passing

- server/db/orders.js
- server/db/seed.js
- server/middleware/authMiddleware.js
- server/middleware/orderRoutes.js
Finally got them working hopefully they'll work for everybody's
> Orderroutefix

- server/middleware/orderRoutes.js
> Add and order history rount

- client/src/components/orders/userOrders.jsx
I think this is finished, was unable to test with a logged in user
> Ordersfrontend

- client/vite.config.js
- server/middleware/authMiddleware.js
- server/middleware/authRoutes.js
- server/middleware/userRoutes.js
I hope no one else was working on this
> Tryingtogetlogin

- client/README.md
- client/src/App.jsx
- client/src/components/Cart.jsx
- client/src/components/paymentForm.jsx
- client/src/components/paymentForm.module.scss
- client/src/pages/user/Checkout.jsx
- client/src/styles/scss/components/_stripe_elements.scss
- client/src/styles/scss/variables/_variables.scss
- server/API.js
- server/db/carts.js
- server/db/payments.js
- server/db/seed.js
- server/middleware/paymentRoutes.js
able to get an order created using this CURL command
curl -X POST http://localhost:3000/api/payment \
-H "Content-Type: application/json" \
-d '{
"userId": "USER_ID_HERE",
"email": "admin@admin.com",
"cartItems": [
{"product_id": 3, "price": 38.34, "quantity": 2}
],
"shippingAddress": "123 Test St"
}'
checkout.jsx now loads from newly created paymentForm.jsx component. PaymentForm should process an order once checkout is properly loading from cart. commitint changes and pushing so everyone can have it
> Stripe checkout process complete

- client/src/pages/LogRegAuth/Login.jsx
It was trying to call the frontend. Fixed to call from the backend
> Fixed login page

- client/src/pages/LogRegAuth/Register.jsx
- server/API.js
Got registration working.  Fixed the CORS router. It should be the port the server looks for. Once the server is running you can test registering a user with this command
$ curl -X POST http://localhost:3000/api/auth/register \
-H "Content-Type: application/json" \
-d '{"name":"Test User","email":"test@test.com","password":"test1234"}'
You should get a response like {"user":{"id":"UUID","email":"test@test.com","name":"Test User","user_role":"customer"},"token":"JWTTOKEN"}
On the front end once you close the alert it redirects you to the dashboard page
> Registration Fix

- client/src/components/Cart.jsx
- client/src/components/paymentForm.jsx
- client/src/pages/user/Checkout.jsx
- client/src/utils/cart.js
- client/vite.config.js
- node_modules/.package-lock.json
- package-lock.json
- package.json
- server/API.js
- server/db/carts.js
- server/middleware/authMiddleware.js
- server/middleware/cartRoutes.js
- server/middleware/paymentRoutes.js
- server/startServer.js
Cart update. Carts now working and saving items to a cookie for the user. First log in and youll see a JWT key in a console log. Plug that key into the YOUR_KEY slot in the command below
curl -X POST "http://localhost:3000/api/carts" \
-H "Authorization: Bearer YOUR_KEY" \
-H "Content-Type: application/json" \
-d '{}'
This should create an empty cart. You can add items to the cart like so. Make sure to double check product_ids with ones in your db
curl -X POST "http://localhost:3000/api/carts" \
-H "Authorization: Bearer YOUR_KEY" \
-H "Content-Type: application/json" \
-d '{"product_id": 2, "quantity": "2"}'
This should return all items in the cart
curl -X GET "http://localhost:3000/api/carts" \
-H "Authorization: Bearer YOUR_KEY"
Once items are added to the cart they should show up on …
> Cart sessions

- client/src/components/products/productDetails.jsx
> i am an idiot

- client/src/App.jsx
- client/src/components/MobileNav.jsx
- client/src/components/Navbar.jsx
- css/App.css
> Mobile nav

- client/src/App.jsx
- client/src/pages/Admin/AdminLayout.jsx
- client/src/styles/scss/App.scss
- client/src/styles/scss/components/_admin_dash.scss
- node_modules/.package-lock.json
- node_modules/dotenv/CHANGELOG.md
- node_modules/dotenv/README-es.md
- node_modules/dotenv/README.md
- node_modules/dotenv/lib/main.js
- node_modules/dotenv/package.json
- node_modules/is-promise/index.d.ts
- node_modules/is-promise/package.json
- package-lock.json
> Admin Console

- client/src/App.jsx
- client/src/pages/Admin/AdminLayout.jsx
- client/src/pages/Admin/AdminSidebar.jsx
- client/src/pages/Admin/AdminTopbar.jsx
- client/src/styles/scss/App.scss
- client/src/styles/scss/components/_admin_inventory.scss
- client/src/styles/scss/components/_admin_orders.scss
- client/src/styles/scss/components/_admin_sidebar.scss
- client/src/styles/scss/components/_admin_topbar.scss
- client/src/styles/scss/layout/_admin_layout.scss
- css/App.css
> Admin Console is _functional_. It does not look pretty, but I will be fixing that soon.
> - [x] Admin Console functionally designed, not cleanly styled.

- client/src/App.jsx
- client/src/pages/user/UserOrders.jsx
- server/db/db.js
- server/db/seed.js
- server/middleware/orderRoutes.js
> Adding in cancelled orders

- package.json
With my recent push there are now 4 database commands, one for the initial seed, one for images and one for genres. update the seed script to run everything when called. The artist_details should be added with the initial seed.
> server scripts fix

- client/package-lock.json
- client/src/components/paymentForm.jsx
- client/src/pages/Admin/AdminOrders.jsx
- client/src/pages/LogRegAuth/Login.jsx
- client/src/pages/user/Checkout.jsx
- client/src/pages/user/OrderConfirmation.jsx
- Added full shipping form fields (name, address, city, state, zip, phone)
- Guests can now successfully complete checkout without logging in
- Orders are saved with user_id = null for guests
- Stripe payment works for both guests and logged-in users (Stripe would not work when I tried checking out as a guest)
- Confirmation page renders updated shipping details + cart item names instead of just the ID number --> cleaned up missing product name issue (description now shown instead of item.title)
> Checkout form

- client/src/components/Cart.jsx
- client/src/components/products/productDetails.jsx
- client/src/pages/Home.jsx
Conditional button issue on details page 
> The 'Add to Bag' button only rendered if the user was logged in
Cart had also been allowing negative values
> Cart button & cart quantity issues

- client/src/components/Cart.jsx
- client/src/styles/scss/global_components/_product_card.scss
- client/src/styles/scss/layout/_cart.scss
- client/src/styles/scss/layout/_footer.scss
- client/src/styles/scss/layout/_product_details.scss
> Cart final styles

- client/src/App.jsx
- client/src/pages/user/Account.jsx
- client/src/pages/user/EditAccount/EditAddress.jsx
- client/src/pages/user/EditAccount/EditBillingInfo.jsx
- client/src/pages/user/EditAccount/EditContactInfo.jsx
- client/src/pages/user/EditAccount/EditShippingAddress.jsx
- client/src/pages/user/ManageAccount.jsx
- client/src/styles/scss/App.scss
- client/src/styles/scss/user_components/_edit_address.scss
- client/src/styles/scss/user_components/_edit_billing_info.scss
- client/src/styles/scss/user_components/_edit_contact_info.scss
- client/src/styles/scss/user_components/_manage_account.scss
Finished up managing account and added link
> Managing account

- client/src/components/FilterBar.jsx
- client/src/components/Navbar.jsx
- client/src/components/products/ProductCard.jsx
- client/src/pages/Admin/Inventory.jsx
- client/src/pages/Home.jsx
- client/src/styles/scss/admin_components/_account_dropdown.scss
- client/src/styles/scss/animations/_animations.scss
- client/src/styles/scss/global_components/_filterBar.scss
- client/src/styles/scss/global_components/_nav.scss
- client/src/styles/scss/global_components/_product_card.scss
- client/src/styles/scss/layout/_home.scss
- client/src/styles/scss/layout/_order_confirmation.scss
- client/src/styles/scss/layout/_product_details.scss
- client/src/styles/scss/variables/_themes.scss
> styes_Home final

- client/src/components/paymentForm.jsx
- client/src/context/AuthContext.jsx
- client/src/pages/user/Account.jsx
- client/src/pages/user/EditAccount/EditAddress.jsx
- client/src/pages/user/EditAccount/EditBillingInfo.jsx
- client/src/pages/user/EditAccount/EditContactInfo.jsx
- client/src/pages/user/ManageAccount.jsx
- client/src/styles/scss/user_components/_edit_address.scss
- client/src/styles/scss/user_components/_edit_billing_info.scss
- client/src/styles/scss/user_components/_edit_contact_info.scss
- client/src/styles/scss/user_components/_manage_account.scss
- server/middleware/paymentRoutes.js
- server/middleware/userRoutes.js
implement account management UI:
- Styled Manage Account page with card layout somewhat
- Refactored EditAddress, EditContactInfo, and EditBillingInfo components
- Ensured shipping info pre-fills from user profile if empty
- Added backend route to fetch latest billing info per user - NOT WORKING IDK WHY
- Confirmed billing info saves correctly after order placement - IN PROGRESS
> Tweaks to user account management

- .gitignore
I am having major git issues today, don't know why this is pushing to main but it should not hurt anything
> Update .gitignore to stop ignoring important public folders

- client/src/pages/LogRegAuth/Register.jsx
- client/src/pages/user/Checkout.jsx
- server/db/db.js
- server/middleware/cartRoutes.js
Got the register and check out working for guest users
> Squashing bugs

- client/src/pages/user/ManageAccount.jsx
- client/src/styles/scss/user_components/_manage_account.scss
> Acct mgmt styling final

- client/src/components/Cart.jsx
- client/src/components/products/ProductCard.jsx
- client/src/components/products/productDetails.jsx
- client/src/styles/scss/global_components/_product_card.scss
- client/src/styles/scss/layout/_product_details.scss
- client/src/styles/scss/variables/_themes.scss
- css/App.css
Noodles of all sorts. Soba. Ramen. Italian??? or is that pasta ?
> howdy yall

- client/.gitignore
- client/babel.config.cjs
- client/jest.config.cjs
- client/package-lock.json
- client/package.json
- client/src/setupTests.js
- client/src/tests/Login.test.jsx
- client/src/tests/ProductCard.test.jsx
- client/src/tests/Register.test.jsx
Set up Jest testing framework and add unit tests for `Login`, `Register`, and `ProductCard` components
- Installed and configured Jest with Babel for React component testing
- Added `jest.config.cjs` and `babel.config.cjs` for test environment setup
- Created `setupTests.js` to include global DOM matchers
- Mocked components using import.meta.env (e.g. `MarketPrice`, `WishlistButton`)
- Added tests for Login and Register forms (input rendering and user typing)
- Added test for `ProductCard` (renders data, calls handlers on click)
> Setup/config for React unit tests + Login, Register, ProductCard tests

- client/src/components/products/productDetails.jsx
fetch single product by id to prevent missing details on paginated pages
> fix(productDetails)
